title: "Luis Palomero"
description: "Científico de datos | Investigador | Candidato a Doctor en Informática (UJI)"

theme: jekyll-theme-minimal

nav:
  - title: "Inicio"
    url: /
  - title: "Publicaciones"
    url: /publicaciones
  - title: "Ensayos"
    url: /ensayos
  - title: "Contacto"
    url: /contacto
