title: "LP"
description: "Científico de datos | Investigador | Candidato a Doctor en Informática (UJI)"
author:
  name: "Luis Palomero"
  avatar: "/assets/img/avatar.jpg"
  bio: "Investigador en IA aplicada a finanzas y bioinformática"

favicon: /favicon.ico
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

nav_order: 1
nav:
  - title: "Inicio"
    url: /
  - title: "Publicaciones"
    url: /publicaciones
  - title: "Ensayos"
    url: /ensayos
  - title: "Contacto"
    url: /contacto
