title: "LP"
description: "Científico de datos | Investigador | Candidato a Doctor en Informática (UJI)"
author: "Luis Palomero"
locale: "es-ES"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: "Luis Palomero"
  avatar: "/assets/img/avatar.jpg"
  bio: "Investigador en IA aplicada a finanzas y bioinformática"
  location : "Castellón de la Plana, España"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lpalomerol@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/luispalomero/"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-9144-1017"

favicon: /favicon.ico

# -----------------------
# OPCIÓN 1: Header Pages
# -----------------------
# Esto siempre funciona en GitHub Pages. 
# Activa los links en la cabecera directamente desde los ficheros .md
#header_pages:
#  - index.md
#  - publicaciones.md
#  - ensayos.md
#  - contacto.md

# -----------------------
# OPCIÓN 2: Navigation (comentada por ahora)
# -----------------------
# Descomenta esto si prefieres usar el sistema nativo de Minimal Mistakes.
 navigation:
   main:
     - title: "Inicio"
       url: /
     - title: "Publicaciones"
       url: /publicaciones/
     - title: "Ensayos y artículos"
       url: /ensayos/
     - title: "Contacto"
       url: /contacto/

# Layout por defecto con sidebar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide
