title: "LP"
description: "Científico de datos | Investigador | Candidato a Doctor en Informática (UJI)"

remote_theme: just-the-docs/just-the-docs
nav_order: 1
nav:
  - title: "Inicio"
    url: /
  - title: "Publicaciones"
    url: /publicaciones
  - title: "Ensayos"
    url: /ensayos
  - title: "Contacto"
    url: /contacto
