title: "LP"
description: "Científico de datos | Investigador | Candidato a Doctor en Informática (UJI)"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: "Luis Palomero"
  avatar: "/assets/img/avatar.jpg"
  bio: "Investigador en IA aplicada a finanzas y bioinformática"
  location : "Castellón de la Plana, España"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lpalomerol@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/luispalomero/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lpalomerol"

favicon: /favicon.ico

# Navegación principal
main:
  - title: "Inicio"
    url: /
  - title: "Publicaciones"
    url: /publicaciones/
  - title: "Ensayos"
    url: /ensayos/
  - title: "Contacto"
    url: /contacto/

# Layout por defecto con sidebar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
